import type { Metadata } from "next";
import Nav from "./Nav";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "My Electronics",
  description: "Generated by create next app - electricalfaris@gmail.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="page-wrapper">
          <Nav />
          
          {children}
        </div>
      </body>
    </html>
  );
}
